config/routes.rb
Rails.application.routes.draw do

  scope(module: :user) do
    get('login', to: 'authentication#login')
    post('login', to: 'authentication#login')
    get('logout', to: 'authentication#login')
    get('index', to: 'user#index')
    get('registered_sessions', to: 'user#registered_sessions')
    get('course/register', to: 'course#register', as: :course_register1)
    get('course/register/:course', to: 'course#register', as: :course_register2)
    get('course/register/:course/:session', to: 'course#register', as: :course_register3)
    get('course/cancel/:id', to: 'course#cancel', as: :course_cancel)
    post('course/cancel/:id', to: 'course#cancel')
    post('course/register/:course/:session', to: 'course#register', as: :course_register4)
  end

  scope(module: :admin) do
    get('admin/login', to: 'authentication#login')
    post('admin/login', to: 'authentication#login')
    get('admin/logout', to: 'authentication#logout')
    get('admin/index')
    get('department/insert', as: :insert_department)
    post('department/insert')
    get('department/update/:id', to: 'department#update', as: :update_department)
    post('department/update/:id', to: 'department#update')
    get('department/delete/:id', to: 'department#delete', as: :delete_department)
    post('department/delete/:id', to: 'department#delete')
    get('course/:id', to: 'course#details', as: :course_details , constraints: {id: /[0-9]+/})
    get('course/insert', as: :insert_course)
    post('course/insert')
    get('course/update/:id', to: 'course#update', as: :update_course)
    post('course/update/:id', to: 'course#update')
    get('course/delete/:id', to: 'course#delete', as: :delete_course)
    post('course/delete/:id', to: 'course#delete')
    get('session/:id', to: 'session#details', as: :session_details)
    get('member/insert', as: :insert_member)
    post('member/insert')
    get('member/update/:id', to: 'member#update', as: :update_member)
    post('member/update/:id', to: 'member#update')
    get('member/delete/:id', to: 'member#delete', as: :delete_member)
    post('member/delete/:id', to: 'member#delete')
  end

  root(to: 'user/authentication#login')

end

app/models/course.rb
class Course < ApplicationRecord

  has_many(:requirements, foreign_key: :require_course_id, inverse_of: :require_course, dependent: :destroy)
  has_many(:sessions, dependent: :destroy)
  # has_many(:precursor, through: :course_associations)
  has_many(:required_departments, through: :requirements)
  # has_many(:successor, through: :course_associations)
  validates(:name, presence: true)
  validates(:code, presence: true, uniqueness: true)

  attribute(:required, :boolean)
  attribute(:registered, :boolean)

  def to_s
    code << ' - ' << name
  end

end

app/controllers/admin/course_controller.rb
class Admin::CourseController < Admin::AdminBaseController

  def details
    @record = corresponding_model.find(params.fetch(:id))
  end

  def fields
    [:name, :code, :description, required_department_ids: [], sessions: [[:start_time, :end_time]]]
  end

  protected(:fields)

  def prepare_params(params)
    params[:required_department_ids] ||= []
    sessions = params.require(:sessions)
    sessions.keep_if do |_, x|
      begin
        x.require([:start_time, :end_time])
      rescue ActionController::ParameterMissing
        nil
      end
    end
    params[:sessions] = sessions.to_h.values.map do |x|
      @record && Session.find_by(x.map { |k, v| [k, v.in_time_zone] }.to_h, course: @record) || Session.new(x)
    end
    params
  end

  protected(:prepare_params)

end

app/controllers/user/course_controller.rb
class User::CourseController < User::UserBaseController

  def register
    @data = {}
    if params[:course]
      @data[:course] = Course.find(params.fetch(:course))
      if params[:session]
        @data[:session] = Session.find_by!(id: params.fetch(:session), course: @data[:course])
        if params[:commit]
          @data[:session].participants << @current_user unless @data[:session].participants.include?(@current_user)
          redirect_to(course_register1_path)
        end
      else
        @data[:sessions] = @data[:course].sessions
      end
    else
      @data[:courses] = @current_user.registering_courses_details
    end
  end

  def cancel
    @participation = Participation.find_by!(registered_session_id: params.fetch(:id), participant: @current_user)
    if params[:commit]
      @participation.destroy!
      redirect_to(registered_sessions_path)
    end
  end

end

app/helpers/admin/course_helper.rb
module Admin::CourseHelper
end

app/helpers/user/course_helper.rb
module User::CourseHelper
end

app/views/admin/course/details.html.erb
<%= details_of(@record) %>
Sessions :
<%= tableize(@record.sessions,
             id:           nil,
             start_time:   nil,
             end_time:     nil,
             participants: [:participants, :size],
             actions:      ->(datum, _) { link_to('Details', session_details_path(datum.id)) }
    ) %>
<%= link_to('Update', update_course_path(@record.id)) %>
<%= link_to('Delete', delete_course_path(@record.id)) %>

app/views/admin/course/form.html.erb
<% sessions_number = @record && @record.sessions.count || 0 %>
<%= content_tag(:ul) { @record.errors.full_messages.map { |x| content_tag(:li, x) }.join.html_safe } if @record %>
<%= form_tag do %>
    <%= label_tag('course[name]', 'Name') %>
    <%= text_field_tag('course[name]', @record.try(:name), required: true) %>
    <br>
    <%= label_tag('course[code]', 'Code') %>
    <%= text_field_tag('course[code]', @record.try(:code), required: true) %>
    <br>
    <%= label_tag('course[description]', 'Description') %>
    <%= text_area_tag('course[description]', @record.try(:description)) %>
    <br>
    <%= label_tag('course[required_department_ids]', 'Required Department') %>
    <%= select_tag('course[required_department_ids]', options_from_collection_for_select(Department.all, :id, :short_name, @record.try(:required_department_ids)), multiple: true) %>
    <br>
    <%= label_tag('course[sessions][0][start_time]', 'Sessions') %>
    <table id="course_sessions" border="1">
      <tr>
        <th>Start Time</th>
        <th>End Time</th>
        <th>
          <%= button_tag('Insert', id: 'course_sessions_insert') %>
        </th>
      </tr>
      <% @record && @record.sessions.each.with_index do |session, index| %>
          <tr id="course_sessions_<%= index %>">
            <td>
              <%= text_field_tag("course[sessions][#{index}][start_time]", session.start_time, id: "course_sessions_#{index}_start_time") %>
            </td>
            <td>
              <%= text_field_tag("course[sessions][#{index}][end_time]", session.end_time, id: "course_sessions_#{index}_end_time") %>
            </td>
            <td>
              <%= button_tag('Delete', id: "course_sessions_#{index}_delete") %>
            </td>
          </tr>
      <% end %>
      <tr id="course_sessions_%">
        <td>
          <%= text_field_tag('course[sessions][%][start_time]', nil, id: 'course_sessions_%_start_time') %>
        </td>
        <td>
          <%= text_field_tag('course[sessions][%][end_time]', nil, id: 'course_sessions_%_end_time') %>
        </td>
        <td>
          <%= button_tag('Delete', id: 'course_sessions_%_delete') %>
        </td>
      </tr>
    </table>
    <br>
    <%= submit_tag('Submit') %>
<% end %>

<%= javascript_include_tag('jquery3.min.js') %>

<script>
  const $course_sessions_template = jQuery('#course_sessions_\\%');
  const course_sessions_template = $course_sessions_template[0].outerHTML;
  $course_sessions_template.remove();
  var sessions_number = <%= sessions_number %>;
  function delete_course_session (event) {
    event.preventDefault();
    jQuery(this).closest('tr').remove();
    if (jQuery('#course_sessions').find('tr').length == 1)
      insert_course_session(++sessions_number);
  }
  function insert_course_session(index) {
    jQuery('#course_sessions').append(jQuery(course_sessions_template.replace(/%/g, index)));
    jQuery('#course_sessions_' + index + '_delete').click(delete_course_session);
  }
  insert_course_session(sessions_number);
  jQuery(function () {
    for (var t = 0; t <= sessions_number; t++) {
      jQuery('#course_sessions_' + t + '_delete').click(delete_course_session);
    }
    jQuery('#course_sessions_insert').click(function (e) {
      e.preventDefault();
      insert_course_session(++sessions_number);
    });
  });
</script>