config/routes.rb
Rails.application.routes.draw do

  scope(module: :user) do
    get('login', to: 'authentication#login')
    post('login', to: 'authentication#login')
    get('logout', to: 'authentication#login')
    get('index', to: 'user#index')
    get('registered_sessions', to: 'user#registered_sessions')
    get('course/register', to: 'course#register', as: :course_register1)
    get('course/register/:course', to: 'course#register', as: :course_register2)
    get('course/register/:course/:session', to: 'course#register', as: :course_register3)
    get('course/cancel/:id', to: 'course#cancel', as: :course_cancel)
    post('course/cancel/:id', to: 'course#cancel')
    post('course/register/:course/:session', to: 'course#register', as: :course_register4)
  end

  scope(module: :admin) do
    get('admin/login', to: 'authentication#login')
    post('admin/login', to: 'authentication#login')
    get('admin/logout', to: 'authentication#logout')
    get('admin/index')
    get('department/insert', as: :insert_department)
    post('department/insert')
    get('department/update/:id', to: 'department#update', as: :update_department)
    post('department/update/:id', to: 'department#update')
    get('department/delete/:id', to: 'department#delete', as: :delete_department)
    post('department/delete/:id', to: 'department#delete')
    get('course/:id', to: 'course#details', as: :course_details , constraints: {id: /[0-9]+/})
    get('course/insert', as: :insert_course)
    post('course/insert')
    get('course/update/:id', to: 'course#update', as: :update_course)
    post('course/update/:id', to: 'course#update')
    get('course/delete/:id', to: 'course#delete', as: :delete_course)
    post('course/delete/:id', to: 'course#delete')
    get('session/:id', to: 'session#details', as: :session_details)
    get('member/insert', as: :insert_member)
    post('member/insert')
    get('member/update/:id', to: 'member#update', as: :update_member)
    post('member/update/:id', to: 'member#update')
    get('member/delete/:id', to: 'member#delete', as: :delete_member)
    post('member/delete/:id', to: 'member#delete')
  end

  root(to: 'user/authentication#login')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/course.rb
class Course < ApplicationRecord

  has_many(:requirements, foreign_key: :require_course_id, inverse_of: :require_course, dependent: :destroy)
  has_many(:sessions, dependent: :destroy)
  # has_many(:precursor, through: :course_associations)
  has_many(:required_departments, through: :requirements)
  # has_many(:successor, through: :course_associations)
  validates(:name, presence: true)
  validates(:code, presence: true, uniqueness: true)

  attribute(:required, :boolean)
  attribute(:registered, :boolean)

  def to_s
    code << ' - ' << name
  end

end

app/models/course_association.rb
class CourseAssociation < ApplicationRecord

  belongs_to(:precursor, class_name: 'Course')
  belongs_to(:successor, class_name: 'Course')
  validates_uniqueness_of(:successor, scope: :precursor)

end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many(:receipts)
end

app/models/department.rb
class Department < ApplicationRecord

  has_many(:members, dependent: :nullify)
  has_many(:requirements, foreign_key: :required_department_id, inverse_of: :required_department, dependent: :destroy)
  has_many(:require_courses, through: :requirements)
  validates(:short_name, presence: true, uniqueness: true)
  validates(:full_name, presence: true, uniqueness: true)

  def to_s
    short_name << ' - ' << full_name
  end

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to(:receipt)

end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to(:department, optional: true, counter_cache: true)
  has_many(:participations, foreign_key: :participant_id, inverse_of: :participant, dependent: :destroy)
  has_many(:registered_sessions, through: :participations)
  validates(:name, presence: true)
  validates(:student_id, presence: true, uniqueness: true)

  def registering_courses_details
    Course
        .select('"courses".*')
        .select('"required"')
        .select('"registered"')
        .joins('LEFT OUTER JOIN (' <<
                   Requirement
                       .select('"require_course_id"')
                       .select('1 AS "required"')
                       .where(required_department: department)
                       .to_sql <<
                   ') ON "courses"."id" = "require_course_id"')
        .joins('LEFT OUTER JOIN (' <<
                   Session
                       .select('"course_id"')
                       .select('1 AS "registered"')
                       .joins(:participations)
                       .where(participations: {participant: self})
                       .to_sql <<
                   ') ON "courses"."id" = "course_id"')
        .order('"registered DESC"', '"required" DESC', code: :asc)
  end

  def to_s
    student_id << ' - ' << name
  end

end

app/models/participation.rb
class Participation < ApplicationRecord

  belongs_to(:participant, class_name: 'Member', counter_cache: :registered_sessions_count)
  belongs_to(:registered_session, class_name: 'Session', counter_cache: :participants_count)
  validates_uniqueness_of(:registered_session, scope: :participant)

end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many(:receipts)
end

app/models/receipt.rb
class Receipt < ApplicationRecord

  belongs_to(:member)
  belongs_to(:payment_method)
  belongs_to(:currency)

  has_many(:items)

end

app/models/requirement.rb
class Requirement < ApplicationRecord

  belongs_to(:require_course, class_name: 'Course', counter_cache: :required_departments_count)
  belongs_to(:required_department, class_name: 'Department', counter_cache: :require_courses_count)
  validates_uniqueness_of(:require_course, scope: :required_department)

end

app/models/session.rb
class Session < ApplicationRecord

  belongs_to(:course, counter_cache: true)
  has_many(:participations, foreign_key: :registered_session_id, inverse_of: :registered_session, dependent: :destroy)
  has_many(:participants, through: :participations)
  validates(:start_time, presence: true)
  validates(:end_time, presence: true)
  validates_uniqueness_of(:course, scope: [:start_time, :end_time])

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery(with: :exception)
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper

  def details_of(data)
    header = data.class.name.titleize
    body   = data.attributes.map { |name, value| content_tag(:tr, content_tag(:td, name) + content_tag(:td, value)) }.join
    "<table border=\"1\"><tr><th colspan=\"2\">#{header}</th></tr>#{body}</table>".html_safe
  end

  def tableize(data, fields)
    header = fields.keys.map { |x| content_tag(:th, x.to_s.titleize) }.join
    body   = data.map do |x1|
      row = fields.map do |x2, x3|
        raise(TypeError.new('Symbol expected, %s given') % x2.class) unless x2.is_a?(Symbol)
        case x3
          when true, false, nil
            cell = x1.public_send(x2).to_s
          when String, Symbol
            cell = x1.public_send(x3).to_s
          when Array, Hash
            cell = x3.reduce(x1, &:public_send).to_s
          when Proc
            cell = x3.call(x1, x2).to_s
          else
            raise(TypeError.new('true, false, nil, String, Symbol or Proc expected, %s given' % x3.class))
        end
        content_tag(:td, cell.html_safe)
      end.join
      content_tag(:tr, row.html_safe)
    end.join
    "<table border=\"1\"><tr>#{header}</tr>#{body}</table>".html_safe
  end

end

app/helpers/admin/course_helper.rb
module Admin::CourseHelper
end

app/helpers/admin/member_helper.rb
module Admin::MemberHelper
end

app/helpers/admin/session_helper.rb
module Admin::SessionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/course_helper.rb
module User::CourseHelper
end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/views/admin/admin/index.html.erb
Departments :
<%= tableize(@data[:departments],
             id:         nil,
             short_name: nil,
             full_name:  nil,
             members:    [:members, :size],
             actions:    ->(datum, _) do
               link_to('Update', update_department_path(datum.id)) << ' ' <<
                   link_to('Delete', delete_department_path(datum.id))
             end) %>
<%= link_to('Insert', insert_department_path) %>
<br>
<br>
Courses :
<%= tableize(@data[:courses],
             id:          nil,
             code:        nil,
             name:        nil,
             description: nil,
             sessions:    [:sessions, :size],
             actions:     ->(datum, _) do
               link_to('Details', course_details_path(datum.id)) << ' ' <<
                   link_to('Update', update_course_path(datum.id)) << ' ' <<
                   link_to('Delete', delete_course_path(datum.id))
             end) %>
<%= link_to('Insert', insert_course_path) %>
<br>
<br>
Members :
<%= tableize(@data[:members],
             id:                  nil,
             student_id:          nil,
             name:                nil,
             department:          [:department, :to_s],
             phone:               nil,
             registered_sessions: [:registered_sessions, :size],
             actions:             ->(datum, _) do
               link_to('Update', update_member_path(datum.id)) << ' ' <<
                   link_to('Delete', delete_member_path(datum.id))
             end) %>
<%= link_to('Insert', insert_member_path) %>
<br>
<br>
<%= link_to('Log Out', '/admin/logout') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Course Register</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/delete.html.erb
Delete this record?
<br>
<%= details_of(@record) %>
<%= form_tag do
  submit_tag('Yes') <<
      link_to(button_tag('No'), '/admin/index')
end %>